"""Rename testimonial date to created_at

Revision ID: 90b97b6d03c4
Revises: ac0450b9ec2b
Create Date: 2025-05-06 15:06:20.796696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b97b6d03c4'
down_revision = 'ac0450b9ec2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testimonial', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonial', 'created_at')
    # ### end Alembic commands ###
